//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyCommissionHistory
    {
        public int AgencyCommissionHistoryId { get; set; }
        public int AgencyId { get; set; }
        public double OriBasicCommission { get; set; }
        public double OriSeasonCommission { get; set; }
        public double OriCreditLimit { get; set; }
        public double ChBasicCommission { get; set; }
        public double ChSeasonCommission { get; set; }
        public double ChCreditLimit { get; set; }
        public int SiteLocationId { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
