//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessTripFlight
    {
        public int BusinessTripFlightId { get; set; }
        public Nullable<int> BusinessTripId { get; set; }
        public Nullable<System.DateTime> AirDate { get; set; }
        public string AirPort { get; set; }
        public string Destination { get; set; }
        public string Departure { get; set; }
        public string DepartureMin { get; set; }
        public string AirLine { get; set; }
        public Nullable<decimal> AirRate { get; set; }
        public string AirNote { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
