//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessTrip
    {
        public int BusinessTripId { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> AirSub { get; set; }
        public Nullable<decimal> AccomSub { get; set; }
        public Nullable<decimal> GroundSub { get; set; }
        public Nullable<decimal> MealsSub { get; set; }
        public Nullable<decimal> CashSub { get; set; }
        public Nullable<decimal> GrandSub { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ApprovalId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string ApprovalMemo { get; set; }
        public Nullable<int> HqCheckNo { get; set; }
    }
}
