//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessTripAccom
    {
        public int BusinessTripAccomId { get; set; }
        public Nullable<int> BusinessTripId { get; set; }
        public Nullable<System.DateTime> AccomIn { get; set; }
        public Nullable<System.DateTime> AccomOut { get; set; }
        public string City { get; set; }
        public string Hotel { get; set; }
        public Nullable<decimal> AccomRate { get; set; }
        public string AccomNote { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
