//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditMemoPayoutHistory
    {
        public int CreditMemoPayoutHistoryId { get; set; }
        public Nullable<int> OriginalCreditMemoPayoutHistoryId { get; set; }
        public int CreditMemoPayoutId { get; set; }
        public string CheckNo { get; set; }
        public string WireTransferNo { get; set; }
        public decimal PayoutAmount { get; set; }
        public System.DateTime PayoutDate { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
    }
}
