//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormitoryCancelScheduleChange
    {
        public int DormitoryCancelSchdeduleId { get; set; }
        public Nullable<int> ChangeType { get; set; }
        public Nullable<int> OriginalStudentBasicId { get; set; }
        public Nullable<int> NewStudentBasicId { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
    }
}
