//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormitoryCost
    {
        public int DormitoryCostId { get; set; }
        public Nullable<int> SiteLocationId { get; set; }
        public string SchoolName { get; set; }
        public string SchoolLocation { get; set; }
        public Nullable<decimal> DormitoryFee { get; set; }
        public Nullable<decimal> PlacementFee { get; set; }
        public Nullable<decimal> AirportPickUpFee { get; set; }
        public Nullable<decimal> AirportDropOffFee { get; set; }
        public Nullable<decimal> DepositFee { get; set; }
        public Nullable<decimal> ExtralDayFee { get; set; }
    }
}
