//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormitoryHostPrefferedSchool
    {
        public int HostSchoolId { get; set; }
        public int HostId { get; set; }
        public Nullable<int> SiteLocationId { get; set; }
        public string DistanceSchool { get; set; }
        public string DistanceStation { get; set; }
        public string MajorIntersection { get; set; }
        public Nullable<int> ContactUserId { get; set; }
        public Nullable<bool> DefaultHostSchool { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
    }
}
