//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormitoryRegistration
    {
        public int DormitoryRegistrationId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> PickUp { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string ArrivalFlightNo { get; set; }
        public Nullable<decimal> PickUpFee { get; set; }
        public string ArrivalAirLine { get; set; }
        public Nullable<System.TimeSpan> ArriveTime { get; set; }
        public string DepartingFrom { get; set; }
        public Nullable<int> DropOff { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string DepartureFlightNo { get; set; }
        public Nullable<decimal> DropoffFee { get; set; }
        public string DepartureAirLine { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
        public string LeavingFrom { get; set; }
        public Nullable<int> ExtensionFlag { get; set; }
        public Nullable<int> DormitoryWeeks { get; set; }
        public Nullable<int> ExtraDays { get; set; }
        public Nullable<decimal> DormitoryFee { get; set; }
        public Nullable<int> UrgentRequest { get; set; }
        public string UploadedFile { get; set; }
        public string Comments { get; set; }
        public Nullable<int> DormitoryStudentStatus { get; set; }
        public Nullable<int> PlacedUserId { get; set; }
        public Nullable<System.DateTime> PlacedDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
