//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hire
    {
        public int HireId { get; set; }
        public int Department { get; set; }
        public int Genre { get; set; }
        public int Condition { get; set; }
        public string JobTitle { get; set; }
        public string ReasonForHiring { get; set; }
        public string DutiesAndResponsibilities { get; set; }
        public string SkillsAndExperienceAndQualification { get; set; }
        public string SalaryOrWage { get; set; }
        public string EmploymentCategory { get; set; }
        public string HoursOrDaysOfWork { get; set; }
        public string AdditionalComments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<int> ApprovalId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string ApprovalMemo { get; set; }
    }
}
