//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomestayHostFamilyMember
    {
        public int FamilyMemberId { get; set; }
        public Nullable<int> HostId { get; set; }
        public string MemberFirstName { get; set; }
        public string MemberLastName { get; set; }
        public Nullable<System.DateTime> MemberDOB { get; set; }
        public Nullable<bool> MemberGender { get; set; }
        public Nullable<bool> MemberCRC { get; set; }
        public Nullable<bool> MemberLivingHome { get; set; }
        public string Relationship { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
