//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomestayCost
    {
        public int HomestayCostId { get; set; }
        public Nullable<int> SiteLocationId { get; set; }
        public string SchoolName { get; set; }
        public string SchoolLocation { get; set; }
        public Nullable<decimal> JuniorFee { get; set; }
        public Nullable<decimal> Private_FullMealFee { get; set; }
        public Nullable<decimal> Private_HalfMealFee { get; set; }
        public Nullable<decimal> Shared_FullMealFee { get; set; }
        public Nullable<decimal> Shared_HalfMealFee { get; set; }
        public Nullable<decimal> PlacementFee { get; set; }
        public Nullable<decimal> AirportPickUpFee { get; set; }
        public Nullable<decimal> AirportDropOffFee { get; set; }
        public Nullable<decimal> ExtralDayFee { get; set; }
        public Nullable<decimal> InternetFee { get; set; }
    }
}
