//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public Nullable<int> OriginalInvoiceId { get; set; }
        public int InvoiceType { get; set; }
        public int InvoiceIndex { get; set; }
        public string InvoiceNumber { get; set; }
        public int InvoicePartialIndex { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<bool> IsAgencySeasonalRate { get; set; }
        public Nullable<int> ProgramRegistrationId { get; set; }
        public Nullable<int> HomestayRegistrationId { get; set; }
        public Nullable<int> DormitoryRegistrationId { get; set; }
        public Nullable<int> ScholarshipId { get; set; }
        public Nullable<decimal> ScholarshipAmount { get; set; }
        public Nullable<int> ScholarshipWeeks { get; set; }
        public Nullable<int> PromotionId { get; set; }
        public Nullable<int> SiteLocationId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CanceledDate { get; set; }
        public bool IsActive { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsFinancialGurantee { get; set; }
    }
}
