//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageProgramDetail
    {
        public int PackageProgramDetailId { get; set; }
        public Nullable<int> PackageProgramId { get; set; }
        public Nullable<int> InvoiceCoaItemId { get; set; }
        public Nullable<decimal> StandardPrice { get; set; }
        public Nullable<decimal> StudentPrice { get; set; }
        public Nullable<decimal> AgencyPrice { get; set; }
        public string Remark { get; set; }
    }
}
