//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public Nullable<int> OriginalPaymentId { get; set; }
        public int PaymentIndex { get; set; }
        public string PaymentNumber { get; set; }
        public int PaymentPartialIndex { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int InvoiceId { get; set; }
        public int Method { get; set; }
        public Nullable<int> Currency { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public int SiteLocationId { get; set; }
        public Nullable<decimal> ExtraAmount { get; set; }
        public Nullable<int> ExtraType { get; set; }
        public Nullable<System.DateTime> ExtraDate { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
