//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramOtherFeeInfo
    {
        public int ProgramOtherFeeId { get; set; }
        public int ProgramId { get; set; }
        public Nullable<decimal> RegFee { get; set; }
        public Nullable<decimal> JRegFee { get; set; }
        public Nullable<decimal> AcademicFee { get; set; }
        public Nullable<decimal> MaterialFee { get; set; }
        public Nullable<decimal> TestFee { get; set; }
        public Nullable<decimal> PracticeFee { get; set; }
        public Nullable<decimal> ExamFee { get; set; }
        public Nullable<decimal> AdminFee { get; set; }
        public Nullable<decimal> InternFee { get; set; }
        public Nullable<decimal> LCFee { get; set; }
        public Nullable<decimal> SDFee { get; set; }
        public Nullable<decimal> UPFee { get; set; }
        public Nullable<decimal> ACFee { get; set; }
        public Nullable<decimal> CFee { get; set; }
        public Nullable<decimal> SupplyFee { get; set; }
        public Nullable<decimal> UniformFee { get; set; }
        public Nullable<decimal> UAGFee { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public string Comment { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
