//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramClass
    {
        public int ProgramClassId { get; set; }
        public int ProgramId { get; set; }
        public Nullable<int> ProgramCourseId { get; set; }
        public Nullable<int> ProgramCourseLevelId { get; set; }
        public int ProgramClassRoomId { get; set; }
        public int InstructorId { get; set; }
        public int SiteLocationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int ClassWeek { get; set; }
        public Nullable<System.TimeSpan> MondayStartTime { get; set; }
        public Nullable<System.TimeSpan> MondayEndTime { get; set; }
        public Nullable<System.TimeSpan> TuesdayStartTime { get; set; }
        public Nullable<System.TimeSpan> TuesdayEndTime { get; set; }
        public Nullable<System.TimeSpan> WednesdayStartTime { get; set; }
        public Nullable<System.TimeSpan> WednesdayEndTime { get; set; }
        public Nullable<System.TimeSpan> ThursdayStartTime { get; set; }
        public Nullable<System.TimeSpan> ThursdayEndTime { get; set; }
        public Nullable<System.TimeSpan> FridayStartTime { get; set; }
        public Nullable<System.TimeSpan> FridayEndTime { get; set; }
        public Nullable<double> WeekDays { get; set; }
        public Nullable<double> WeekHours { get; set; }
        public Nullable<double> TotalHours { get; set; }
        public bool IsActive { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
