//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int ProgramId { get; set; }
        public Nullable<int> ProgramGroupId { get; set; }
        public string ProgramFullName { get; set; }
        public string ProgramWebName { get; set; }
        public string ProgramShortName { get; set; }
        public string ProgramDescription { get; set; }
        public Nullable<int> ProgramType { get; set; }
        public Nullable<int> UisType { get; set; }
        public Nullable<decimal> EarningCredit { get; set; }
        public Nullable<int> TotalWeeks { get; set; }
        public Nullable<int> TotalSemester { get; set; }
        public Nullable<int> TotalMonth { get; set; }
        public Nullable<double> HoursOfDay { get; set; }
        public Nullable<double> HoursOfWeek { get; set; }
        public Nullable<System.DateTime> EstimatedStartDate { get; set; }
        public string AdmissionRequirement { get; set; }
        public string DiplomaCertificationRequirement { get; set; }
        public Nullable<int> PracticumWeeks { get; set; }
        public Nullable<int> IntershipWeeks { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
        public bool IsActive { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
