//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramOtherInfo
    {
        public int ProgramOtherInfoId { get; set; }
        public int ProgramId { get; set; }
        public string LocalCRC { get; set; }
        public string DoctorNote { get; set; }
        public string Noc { get; set; }
        public string Hrsdc { get; set; }
        public string Reference2 { get; set; }
        public string Reference3 { get; set; }
        public string Eng10 { get; set; }
        public string Math10 { get; set; }
        public string Sience11 { get; set; }
        public string Eng12 { get; set; }
        public string Bio12 { get; set; }
        public string SSience { get; set; }
        public string SMath { get; set; }
        public string SEng { get; set; }
        public string SLBio { get; set; }
        public string SLChemi { get; set; }
        public string Immun { get; set; }
        public string HelpB { get; set; }
        public string Comment { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
