//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarship
    {
        public int ScholarshipId { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public int ScholarshipIndex { get; set; }
        public string ScholarshipMasterNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Weeks { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> MininumRegistrationWeeks { get; set; }
        public string Memo { get; set; }
        public bool IsActive { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ApprovalId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string ApprovalMemo { get; set; }
    }
}
