//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public int StudentMasterIndex { get; set; }
        public string StudentMasterNo { get; set; }
        public int StudentIndex { get; set; }
        public string StudentNo { get; set; }
        public Nullable<int> Title { get; set; }
        public string FirstName { get; set; }
        public string LastName1 { get; set; }
        public string LastName2 { get; set; }
        public string MiddleName1 { get; set; }
        public string MiddleName2 { get; set; }
        public int SiteLocationId { get; set; }
        public string Address1InCanada { get; set; }
        public string Address2InCanada { get; set; }
        public string CityInCanada { get; set; }
        public string ProvinceInCanada { get; set; }
        public string PostalCodeInCanada { get; set; }
        public string PermanentAddress1 { get; set; }
        public string PermanentAddress2 { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentProvince { get; set; }
        public string PermanentPostalCode { get; set; }
        public Nullable<int> PermanentCountry { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int StudentType { get; set; }
        public int AcademicStatus { get; set; }
        public string Passport { get; set; }
        public string LoanNo { get; set; }
        public string SIN { get; set; }
        public Nullable<bool> IsHRSDC { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<int> AgencyContactId { get; set; }
        public string ContactName { get; set; }
        public string ContactAddress { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ContactRelationship { get; set; }
        public string Comment { get; set; }
        public byte[] Picture { get; set; }
        public bool Gender { get; set; }
        public Nullable<int> MarketerId { get; set; }
        public Nullable<int> VisaStatus { get; set; }
        public Nullable<System.DateTime> VisaStart { get; set; }
        public Nullable<System.DateTime> VisaEnd { get; set; }
        public Nullable<int> WorkPermitStatus { get; set; }
        public Nullable<System.DateTime> WorkPermitStart { get; set; }
        public Nullable<System.DateTime> WorkPermitEnd { get; set; }
        public bool Insurance { get; set; }
        public Nullable<System.DateTime> InsuranceStart { get; set; }
        public Nullable<System.DateTime> InsuranceEnd { get; set; }
        public Nullable<decimal> InsuranceDayFee { get; set; }
        public Nullable<decimal> InsuranceTotal { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<bool> IsOptOut { get; set; }
        public bool IsActive { get; set; }
        public int CreatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OldSeqId { get; set; }
    }
}
