//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp2016.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_KGIC
    {
        public int StudentId { get; set; }
        public Nullable<int> StudentMasterIndex { get; set; }
        public Nullable<int> StudentMasterNo { get; set; }
        public Nullable<int> StudentIndex { get; set; }
        public string StudentNo { get; set; }
        public Nullable<int> Title { get; set; }
        public string FirstName { get; set; }
        public string LastName1 { get; set; }
        public string LastName2 { get; set; }
        public string MiddleName1 { get; set; }
        public string MiddleName2 { get; set; }
        public Nullable<int> SiteLocationId { get; set; }
        public string Address1InCanada { get; set; }
        public string Address2InCanada { get; set; }
        public string CityInCanada { get; set; }
        public string ProvinceInCanada { get; set; }
        public string PostalCodeInCanada { get; set; }
        public string PermanentAddress1 { get; set; }
        public string PermanentAddress2 { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentProvince { get; set; }
        public string PermanentPostalCode { get; set; }
        public Nullable<int> PermanentCountry { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email2 { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> StudentType { get; set; }
        public Nullable<int> AcademicStatus { get; set; }
        public string Passport { get; set; }
        public string LoanNo { get; set; }
        public string SIN { get; set; }
        public Nullable<bool> IsHRSDC { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<int> AgencyContactId { get; set; }
        public string ContactName { get; set; }
        public string ContactAddress { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ContactRelationship { get; set; }
        public string Comment { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> MarketerId { get; set; }
        public Nullable<int> VisaStatus { get; set; }
        public Nullable<System.DateTime> VisaStart { get; set; }
        public Nullable<System.DateTime> VisaEnd { get; set; }
        public Nullable<int> WorkPermitStatus { get; set; }
        public Nullable<System.DateTime> WorkPermitStart { get; set; }
        public Nullable<System.DateTime> WorkPermitEnd { get; set; }
        public Nullable<bool> Insurance { get; set; }
        public Nullable<System.DateTime> InsuranceStart { get; set; }
        public Nullable<System.DateTime> InsuranceEnd { get; set; }
        public Nullable<decimal> InsuranceDayFee { get; set; }
        public Nullable<decimal> InsuranceTotal { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<bool> IsOptOut { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OldSeqId { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string HomeAddr { get; set; }
        public string HomeCountry { get; set; }
        public string HomeNum { get; set; }
        public string BusinessNum { get; set; }
        public string FaxNum { get; set; }
        public string Email1 { get; set; }
        public string CanadaPhone { get; set; }
        public string EF_name { get; set; }
        public string EL_name { get; set; }
        public string Relationship { get; set; }
        public string EmergencyNum { get; set; }
        public string Status { get; set; }
        public string AboutKGIC { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string RegPlace { get; set; }
        public string HomeCity { get; set; }
        public string HomeProv { get; set; }
        public string HomeZipCode { get; set; }
        public string LocationCountry { get; set; }
        public bool Newsletter { get; set; }
        public bool UsePicture { get; set; }
        public Nullable<System.DateTime> FirstComeDate { get; set; }
        public string FirstComeCity { get; set; }
        public bool WantUniv { get; set; }
        public bool WantPathway { get; set; }
        public Nullable<System.DateTime> VisaEndDate { get; set; }
        public Nullable<System.DateTime> VisaStartDate { get; set; }
        public Nullable<System.DateTime> WorkingPermitStartDate { get; set; }
        public Nullable<System.DateTime> WorkingPermitEndDate { get; set; }
        public string WorkingPermit { get; set; }
    }
}
